### ISSUE TITLE
scaler fx options still not working

### ISSUE THREAD

**Issue by mrfpga** [jotego/jtbin#171]
Dear jotego, thank you for your quick bugfix release for the CPS1 core for MiSTer. Unfortunately the scaler fx options are still not working. Additionally, the HQ2x option is missing now.

**Comment by jotego** [comment]
Please run the updater again. 
The HQ2X option is a bit problematic for large cores and it causes compilation to be slow and fail often. A large percentage of users also hate HQ2X. That's why I have disabled it in some CPS compilations.
I may try re-enabling it back for future updates that can take longer to compile.
