### ISSUE TITLE
Strange artifacting in Street Fighter 2

### ISSUE THREAD

**Issue by chanunnaki** [jotego/jtbin#204]
Doesn't seem to occur in other cores, at least not that I have noticed. I've just seen it in SF2 and SF2:Turbo so far.

Basically, single pixel green vertical lines all across the image. It might just be something to do with my setup. I will do some more testing and see if I spot any more. 

![IMAGE 2021-03-26 21:42:20](https://user-images.githubusercontent.com/49243628/112695502-24d59c80-8e7c-11eb-93a2-eb4c02fad681.jpg)
![IMAGE 2021-03-26 21:42:22](https://user-images.githubusercontent.com/49243628/112695516-2a32e700-8e7c-11eb-98dc-7e6ea54eb2d5.jpg)

**Comment by chanunnaki** [comment]
It's happening in all CPS1 games.

**Comment by chanunnaki** [comment]
I'm connecting to a Dell 2007FP in 1600x1200 resolution over VGA port with the following video mode:
video_mode=1600,64,192,304,1200,1,3,46,162000

I can confirm it doesn't happen over VGA

**Comment by jotego** [comment]
I think this is not related to the core, but to MiSTer scaler logic. So maybe the right place for this issue is [here](https://github.com/MiSTer-devel/Template_MiSTer). They may have it fixed already, I don't know. I update the MiSTer framework every 4-6 months because it tends to be a disruptive process. I will update the framework again in the summer.
