### ISSUE TITLE
Passing Shot, missing flip screen option

### ISSUE THREAD

**Issue by InsertDiskTwo** [jotego/jtbin#251]
Passing Shot does not have a flip screen option. I have a monitor which I can rotate 90 degree to play games in TATE mode, but it only turns to one side. Usually I use the flip screen option to turn the picture round, but as Passing Shot core does not have this option, I can only play it upside down :)

**Comment by jotego** [comment]
The problem with the sprites is that System16 has them written in memory with an arbitrary size. The game tells the sprite engine where to start and the how much to add to that address to get to the next line (the line _pitch_). The game finds the end of each line with a marker. Each line can have an arbitrary size. When the game wants to flip the sprite, it tells the sprite engine the last position, tells it to count backwards and uses a negative pitch value.
If the sprite engine were to flip the sprite on its own, it would have to find the last address and negate the pitch, but the last address found by scanning may not be the right one to use as the flip start as end-of-line markers can be at an arbitrary position.
On top of that, the extra effort to find that last memory address will delay the sprite engine and that may result in graphic glitches.
Because of these reasons, I don't plan to implement a hardware flip for System 16. By enabling the frame buffer it is possible to rotate the image in MiSTer as a workaround -at the cost of 1-frame delay
Sorry to bring bad news.
