### ISSUE TITLE
Wrong number of health bars in Golden axe

### ISSUE THREAD

**Issue by pacoarcade** [jotego/jtbin#269]
Since some releases Golden axe shows 5 health bars instead of three for normal difficulty. Setting 'Hardest' via DIP switches doesn't change this and there are still 5 health bars instead of one.

**Comment by jotego** [comment]
@atrac17 could you check this out, please?

**Comment by atrac17** [comment]
Will do.

**Comment by paulb-nl** [comment]
Not tested but I think this should be correct:

````xml
<dip name="Difficulty" bits="10,13" values="10,11,14,15,13,7,5,0" ids="Easiest,Easier,Easy,Normal,Hard,Harder,Hardest,Special"/>
````

**Comment by MJY71** [comment]
All of the valid options are now present, but are out of order compared against the game's DIP switch settings. When you have that service menu open in the background and cycle through them in the OSD, the only one that matches is 'Normal'.

I'll try to look at them later today if I have the time.

**Comment by paulb-nl** [comment]
I think I had the bits reversed. Try this:
````xml
<dip name="Difficulty" bits="10,13" values="5,13,7,15,11,14,10,0" ids="Easiest,Easier,Easy,Normal,Hard,Harder,Hardest,Special"/>
````

**Comment by atrac17** [comment]
This is fixed pending other work on System16.

**Comment by jotego** [comment]
Thank you for your comments. I see where the problem is and I have fixed it. Except, some values are wrong in MAME too. I have created an issue about it [here](https://github.com/mamedev/mame/issues/9602).
For now, I have fixed it to at least work like MAME. I prefer not to correct the values swapped in MAME and wait until they fix it.
